### ISSUE TITLE
Hubspot removes DOCTYPE from HTML email sent via API

### ISSUE THREAD

**Issue by NickiPR** [Badsender-com/esp-html-bugs#17]
Hubspot is removing the DOCTYPE when receiving a HTML email sent via their API.
Creating a custom HTML mail and sending it via API to Hubspot will remove the doctype and make the email not responsive.

**Comment by NickiPR** [comment]
I found the solution.
When creating the API, you basically create a blank template inside of Hubspot every time.
Inside of that template, you will have to manually input the doctype. This can be done via the API, so now it runs smoothly.
What a hazzle - i hope no one will need this advice

**Comment by jloriaux** [comment]
Thank you very much for contributing Nicki !
